[package]
name = "example"
version = "0.1.0"
authors = ["Noah Huesser <nh@technokrat.ch>"]
edition = "2018"

[dependencies]
reactor = { path = "../reactor" }
reactor-derive = { path = "../reactor-derive" }